-- programmers: 취소되지 않은 진료 예약 조회하기

SELECT A.APNT_NO, B.PT_NAME, A.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A
JOIN PATIENT AS B
ON A.PT_NO = B.PT_NO

JOIN DOCTOR AS C
ON A.MDDR_ID = C.DR_ID

WHERE A.APNT_CNCL_YN = 'N'
    AND DATE_FORMAT(A.APNT_YMD, "%Y-%m-%d") = '2022-04-13'
    AND A.MCDP_CD = 'CS'

ORDER BY A.APNT_YMD;