-- programmers: 대여 기록이 존재하는 자동차 리스트 구하기

SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
ON A.CAR_ID = B.CAR_ID
WHERE CAR_TYPE = '세단'
    AND MONTH(START_DATE) = 10
ORDER BY CAR_ID DESC;