-- programmers: 조건에 맞는 사원 정보 조회하기

SELECT SUM(SCORE) AS SCORE, B.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM HR_EMPLOYEES AS A
JOIN HR_GRADE AS B
ON A.EMP_NO = B.EMP_NO
GROUP BY YEAR, EMP_NO
HAVING B.YEAR = '2022'
ORDER BY 1 DESC -- 첫번째 SELECT 컬럼
LIMIT 1;