-- programmers: 조건에 맞는 사용자와 총 거래금액 조회하기

SELECT B.USER_ID, B.NICKNAME, SUM(PRICE) AS PRICE
FROM USED_GOODS_BOARD AS A
JOIN USED_GOODS_USER AS B
ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY USER_ID
HAVING PRICE >= 700000
ORDER BY PRICE;