-- programmers: 자동차 대여 기록 별 대여 금액 구하기

SELECT DISTINCT B.HISTORY_ID,
    ROUND(
        A.DAILY_FEE *
        CASE
            WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 90
                THEN (1 - MAX(CASE WHEN C.DURATION_TYPE = '90일 이상' THEN C.DISCOUNT_RATE / 100 ELSE 0 END))
            WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 30
                THEN (1 - MAX(CASE WHEN C.DURATION_TYPE = '30일 이상' THEN C.DISCOUNT_RATE / 100 ELSE 0 END))
            WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 7
                THEN (1 - MAX(CASE WHEN C.DURATION_TYPE = '7일 이상' THEN C.DISCOUNT_RATE / 100 ELSE 0 END))
            ELSE 1
        END * (DATEDIFF(B.END_DATE, B.START_DATE) + 1)
    ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE = '트럭'
GROUP BY B.HISTORY_ID
ORDER BY FEE DESC, B.HISTORY_ID DESC;