-- programmers: 특정 물고기를 잡은 총 수 구하기

SELECT COUNT(A.FISH_TYPE) AS FISH_COUNT
FROM FISH_INFO AS A
INNER JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.FISH_TYPE IN (SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER')