-- programmers: 저자 별 카테고리 별 매출액 집계하기

SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES*A.PRICE) AS TOTAL_SALES
FROM BOOK AS A

JOIN AUTHOR AS B
ON A.AUTHOR_ID = B.AUTHOR_ID

JOIN BOOK_SALES AS C
ON A.BOOK_ID = C.BOOK_ID

WHERE YEAR(C.SALES_DATE) = 2022 AND MONTH(C.SALES_DATE) = 1
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC;